### PR TITLE
Makes it "focusable" when in "select" mode

### PR DESCRIPTION
**Pull request by andypandy**
- Adds element to tab index when in "<select>" mode.
- Adds "on focus" event to trigger showing the dropdown
- Adds an "un focus" event for if they tab away

### CODE REVIEW

**Comment by andypandy** [comment]
This introduces a bug where when you click it also triggers the focus event. It needs to be reverted. Sorry!

**Comment by jseppi** [comment]
Oh whoops, I also missed that behavior.

**Comment by andypandy** [comment]
I tried figuring out getting it to choose w/ stopImmediatePropogation but
couldn't get anything to work.

**Comment by jseppi** [comment]
I ended up reverting -- binding to focus has a bunch of weird side effects that are hard to properly deal with.

**Pull request merged**
